permalink: /:year/:month/:day/:title
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - package.json
    - postcss.config.js
    - purgecss.config.js
    - vendor
    - yarn.lock
    - Makefile
    - .bundle
    - .ruby-version
strict_front_matter: true
url: /
plugins:
    - jekyll-postcss
    - jekyll-purgecss
